---
- name: Testing AutomationController
  block:
    # 1. Testing AutomationController
    - name: Create AutomationController
      kubernetes.core.k8s:
        name: aap-test
        namespace: "{{ target_namespace }}"
        api_version: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        definition:
          metadata:
            labels:
              opdev: opcap
          spec:
            create_preload_data: true
            route_tls_termination_mechanism: Edge
            garbage_collect_secrets: false
            ingress_type: Route
            loadbalancer_port: 80
            no_log: false
            image_pull_policy: IfNotPresent
            projects_storage_size: 8Gi
            auto_upgrade: true
            task_privileged: false
            projects_storage_access_mode: ReadWriteMany
            web_extra_env: |
              - name: CSRF_TRUSTED_ORIGINS
                value: "['*']"
            set_self_labels: true
            projects_persistence: false
            replicas: 1
            admin_user: admin
            loadbalancer_protocol: http
            nodeport_port: 30080
        state: present
        wait: true
        wait_condition:
          status: "True"
          type: "Running"
          reason: "Successful"
        wait_timeout: 600
        wait_sleep: 10
      register: automationcontroller
    # 2. Testing AAP Route
    - name: Verify the AAP UI is available
      ansible.builtin.uri:
        url: "{{ automationcontroller.result.status.URL }}"
        validate_certs: false
      register: automationcontrollerurl
  rescue:
    - name: Print when failed
      ansible.builtin.debug:
        msg: "AutomationController failed. Err: {{ ansible_failed_result }}"
  always:
    - name: Set boolean result fact
      ansible.builtin.set_fact:
        ac_result: "{{ ((automationcontroller.result is not defined) or
                       ((automationcontroller.result.status.conditions | selectattr('type', 'eq', 'Running') | list | last).status != 'True') or
                       ((automationcontroller.result.status.conditions | selectattr('type', 'eq', 'Running') | list | last).reason != 'Successful') or
                       ((automationcontroller.result.status.conditions | selectattr('type', 'eq', 'Failure') | list | last).status != 'False') or
                       ((automationcontroller.result.status.conditions | selectattr('type', 'eq', 'Failure') | list | last).reason != '') or
                       ((automationcontroller.result.status.conditions | selectattr('type', 'eq', 'Successful') | list | last).status != 'True') or
                       ((automationcontroller.result.status.conditions | selectattr('type', 'eq', 'Successful') | list | last).reason != 'Successful') or
                       (automationcontrollerurl.status is not defined) or
                       (automationcontrollerurl.status != 200)) | bool }}"
    - name: Report result
      ansible.builtin.set_fact:
        assessment_result: "{{ 'fail' if ac_result else 'pass' }}"
# 3. Cleanup
- name: Clean Up AutomationController
  block:
    - name: Delete AutomationController
      kubernetes.core.k8s:
        name: aap-test
        namespace: "{{ target_namespace }}"
        api_version: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        state: absent
        wait: true
  rescue:
    - name: Print when failed
      ansible.builtin.debug:
        msg: "Error: Couldn't delete AutomationController"
# print pass or failed according to assessment_result fact variable
- name: Ansible Automation Platform Operator Results
  ansible.builtin.debug:
    msg: "{{ (assessment_result == 'pass') | ternary('PASS', 'FAIL') }}"
